name: TER

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.4

      - name: Install requirements
        run: composer global require --dev typo3/tailor ^1.3

      - name: Create tag version
        rune: echo `git describe --tags --abbrev=0` >> TAG_VERSION

      - name: Set version in ext_emconf.php
        run: /home/runner/.composer/vendor/bin/tailor set-version --no-docs -- $(cat TAG_VERSION)

      - name: Cleanup before we upload
        run: git reset --hard HEAD && git clean -fx

      - name: Create tag message
        run: echo `git tag -n10 -l $(git describe --abbrev=0 --tags) | sed 's/^[0-9.]*[ ]*//g'` >> TAG_MESSAGE

      - name: Publish to TER
        run: /home/runner/.composer/vendor/bin/tailor ter:publish --comment "$(cat TAG_MESSAGE)" "$(cat TAG_VERSION)" "t3googleanalytics"
