name: TER

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.4

      - name: Install requirements
        run: composer global require --dev typo3/tailor ^1.3

      - name: Cleanup before we upload
        run: git reset --hard HEAD && git clean -fx

      - name: Create tag version
        run: TAG_VERSION=$(git describe --tags --abbrev=0)

      - name: Set version in ext_emconf.php
        run: /home/runner/.composer/vendor/bin/tailor set-version --no-docs -- "$TAG_VERSION"

      - name: Create tag message
        run: TAG_MESSAGE=$(git tag -n10 -l $(git describe --abbrev=0 --tags) | sed 's/^[0-9.]*[ ]*//g')

      - name: Publish to TER
        run: TYPO3_API_USERNAME=${{ secrets.TYPO3_ORG_USERNAME }} TYPO3_API_PASSWORD=${{ secrets.TYPO3_ORG_PASSWORD }} /home/runner/.composer/vendor/bin/tailor ter:publish --comment "$TAG_MESSAGE" "$TAG_VERSION" "t3googleanalytics"
